version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: audi
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

    networks:
      - audi-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/audi?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=root


    ports:
      - "8081:8081"
    networks:
      - audi-network

networks:
  audi-network:
